3.0 preview dev
PolymerElements/iron-validatable-behavior pull request #42
Opened 2018-07-23 19:14 UTC by notwaldorf

2018-07-23 22:39 UTC, bicknellr approved these changes
LGTM; a couple of comments.

2018-07-23 22:39 UTC, bicknellr commented on README.md
> +## &lt;iron-validatable-behavior&gt;
`&lt;iron-validatable-behavior&gt;` -> `` `IronValidatableBehavior` ``

2018-07-23 22:39 UTC, bicknellr commented on README.md
> +  <head>''
There's some extra quotes here.

2018-07-23 22:47 UTC, bicknellr requested changes
There's a few places in here where `Polymer.IronValidatableBehavior` should be changed to `IronValidatableBehavior`.

2018-07-24 00:00 UTC, notwaldorf commented on README.md
> +## &lt;iron-validatable-behavior&gt;
ha my bad

2018-07-24 22:29 UTC, bicknellr approved these changes

2018-07-25 23:02 UTC, merged